### ISSUE TITLE
Audio support

### ISSUE THREAD

**Issue by kalyanijamunkar10** [charliesbot/react-native-media-controls#12]

**Comment by kalyanijamunkar10** [comment]
Have you provided audio support for this?

**Comment by samermurad** [comment]
@kalyanijamunkar10 if you use [react-native-audio-toolkit](https://github.com/futurice/react-native-audio-toolkit), you can integrate the audio support with this library rather easily.
I can send you an implementation example if you would like.

**Comment by kalyanijamunkar10** [comment]
@samermurad yes, please share the implementation.

**Comment by samermurad** [comment]
@kalyanijamunkar10 I uploaded a [gist](https://gist.github.com/samermurad/448187cb0194b939293ae91d2e42a180)  of my solution in a project Im working on... a lot of the code is project related but it demonstrates how you can use  `react-native-audio-toolkit` in collaboration with `react-native-media-controls`.
I hope that helps, let me know if you need any explanation
